const MONTHLYINVESTMENTMIN = 500;
const MONTHLYINVESTMENTMAX = 1000000;
const INVESTMENTPERIODMIN = 1;
const INVESTMENTPERIODMAX = 30;
const RATEOFRETURNMIN = 1;
const RATEOFRETURNMAX = 30;
const YEARLYINCREMENTMIN = 1;
const YEARLYINCREMENTMAX = 12;

module.exports = {
    MONTHLYINVESTMENTMIN,
    MONTHLYINVESTMENTMAX,
    INVESTMENTPERIODMIN,
    INVESTMENTPERIODMAX, 
    RATEOFRETURNMIN,
    RATEOFRETURNMAX, 
    YEARLYINCREMENTMIN,
    YEARLYINCREMENTMAX
}